service: workshop-account

frameworkVersion: ">=1.26.1"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  variableSyntax: '\$\${([\s\S]+?)}'
  environment:
    ROLE_TO_ASSUME: $${self:custom.role}

  iamRoleStatements:
    - Sid: "AllowAssumeRoleToWorkshopAccount"
      Effect: "Allow"
      Action:
        - "sts:AssumeRole"
      Resource: "$${self:custom.role}"
    - Sid: "AllowScheduleRule"
      Effect: "Allow"
      Action:
        - "events:PutRule"
        - "events:DeleteRule"
        - "events:PutTargets"
        - "events:RemoveTargets"
      Resource:
         - Fn::Sub: "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/workshop-*"
    - Sid: "AllowSES"
      Effect: "Allow"
      Action:
        - "ses:sendTemplatedEmail"
      Resource: "*"

custom:
  role: $${opt:role}
  ses-template: workshop-users-create

functions:
  UsersCreate:
    handler: users.create
    name: workshop-user-create
    memorySize: 128
    timeout: 60
    environment:
      LOGIN_URL: http://xebia-france-workshop.signin.aws.amazon.com/console
      SES_CREATE_TEMPLATE: workshop-users-create

  UsersDelete:
    handler: users.delete
    name: workshop-user-delete
    memorySize: 128
    timeout: 60

resources:
  Resources:
    AllowCloudWatch:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: "workshop-user-delete"
        Principal: "events.amazonaws.com"
        SourceArn:
          Fn::Sub: "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*"

    MailCreateTemplate:
      Type: "AWS::SES::Template"
      Properties:
        Template:
          TemplateName: $${self:custom.ses-template}
          SubjectPart: "[AWS] Create users account for {{ workshopName}} into workshop account"
          HtmlPart: |
            <p>Users accounts created</p>
            <b>Login url:</b> {{ loginUrl}}
            <div>{{accounts}}</div>